from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base
from app.models.enums import ProposedChangeStatus, ProposedFieldType


class ProposedChange(Base):
    """A staging row: something the extraction step believes a document says,
    waiting for a human to agree.

    This table is the whole point of the extraction feature. The model never
    writes to EmployeeProject or EmployeeSkill — it emits a typed call, that
    call lands here as `pending`, and only an IT reviewer's explicit accept
    moves content into the real tables (see app/proposals.py). Nothing here
    is searchable or indexed until that happens, which is what makes a wrong
    guess about who "Priya" is a review problem rather than a data-integrity
    one.
    """

    __tablename__ = "proposed_changes"

    # The review queue is always read per-document and filtered by status.
    # Declared here as well as in the migration so `alembic revision
    # --autogenerate` stays silent — an index that exists in the database but
    # not on the model reads as drift and gets "helpfully" dropped by the
    # next autogenerated revision.
    __table_args__ = (
        Index("ix_proposed_changes_doc_status", "source_doc_id", "status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Nullable until resolved: name resolution genuinely fails sometimes,
    # and the directory deliberately contains two people called "Priya
    # Sharma" so that it does. An unresolved row is a real, reviewable
    # outcome — it surfaces in the review UI as "who is this?" — and is
    # strictly better than guessing between two candidates and being right
    # half the time.
    employee_id: Mapped[str | None] = mapped_column(ForeignKey("employees.id"), nullable=True)

    source_doc_id: Mapped[int] = mapped_column(ForeignKey("uploaded_docs.id"), nullable=False)

    field_type: Mapped[ProposedFieldType] = mapped_column(
        Enum(ProposedFieldType, native_enum=False, validate_strings=True), nullable=False
    )

    # Both JSON-encoded into Text, matching AuditLog.fields_returned's
    # precedent — neither SQLite nor Azure SQL has a portable native JSON
    # column type, and this project targets both.
    #
    # raw_extraction is what the model emitted, verbatim and never rewritten;
    # proposed_content is what would actually be committed, and IS rewritten
    # by /correct and /reassign. Keeping both means a reviewer can always see
    # what the document was read as, separately from what the humans turned
    # it into.
    raw_extraction: Mapped[str] = mapped_column(Text, nullable=False)
    proposed_content: Mapped[str] = mapped_column(Text, nullable=False)

    # The extraction step's own confidence, 0.0-1.0. Advisory only: it sorts
    # the review queue, and nothing anywhere auto-accepts above a threshold.
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    status: Mapped[ProposedChangeStatus] = mapped_column(
        Enum(ProposedChangeStatus, native_enum=False, validate_strings=True),
        nullable=False, default=ProposedChangeStatus.pending,
    )

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    # Not a foreign key, same reason as AuditLog.actor_id — who reviewed this
    # has to outlive their employee row.
    reviewed_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    employee = relationship("Employee")
    source_doc = relationship("UploadedDoc")
